export const ROBOTICS_BG = "https://roboclasses.com/cdn/shop/files/d_04_1.jpg?v=1701415307";
export const ROBOTICS_COURSES = '/collections/robotics-courses'
export const PROGRAMMING_COURSES = '/collections/programming-courses'
export const STEM_CLASSES = '/collections/stem-classes'
export const YOUTUBE = 'https://www.youtube.com/channel/UCFew2Gvzvt2Q55bUo6nW7nw'
export const WHATSAPP = 'https://api.whatsapp.com/send/?phone=971561169470&text&type=phone_number&app_absent=0'
export const STUDENT_SPEAKS = '/pages/student-speaks'
export const TRENDING_BLOGS = '/blogs/trending-blogs'
export const ENQUIRY = '/pages/school-college-enquiry'
export const SPOTLIGHT = 'https://www.youtube.com/embed/Tf9iadexBzE'
export const FB_L = 'https://www.facebook.com/roboclasseskids'
export const YT_L = 'https://www.youtube.com/channel/UCFew2Gvzvt2Q55bUo6nW7nw'
export const INSTA_L = 'https://www.instagram.com/roboclasses'
export const X_L= 'https://x.com/ClassesRobo'
export const IN_L = 'https://www.linkedin.com/company/robo-classes'
